# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'week1/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: week1
          output_dir: week1
          # images_dir: docs/images
          # for example <img src="./images/file-name.png">
          #Â image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: week1
